# Generated by Django 3.1 on 2020-08-14 11:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testingprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=1000)),
                ('pin_code', models.PositiveIntegerField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('contact_no', models.PositiveBigIntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('availablity', models.PositiveSmallIntegerField()),
                ('testing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=1000)),
                ('pin_code', models.PositiveIntegerField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('contact_no', models.PositiveBigIntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('total_beds', models.PositiveSmallIntegerField()),
                ('occupied_beds', models.PositiveSmallIntegerField()),
                ('available_beds', models.PositiveSmallIntegerField()),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
