# Generated by Django 3.1 on 2020-08-14 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200814_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='contact_no',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='testingprofile',
            name='contact_no',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
