# Generated by Django 3.1 on 2020-08-18 15:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20200814_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naiveuser_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=1000)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('contact_no', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
