# Generated by Django 3.1 on 2020-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testingprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
