# Generated by Django 3.1 on 2020-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200818_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testingprofile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
