# Generated by Django 3.1 on 2020-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201002_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='door_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='state',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='street',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='testingprofile',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='testingprofile',
            name='door_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='testingprofile',
            name='state',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='testingprofile',
            name='street',
            field=models.CharField(max_length=40),
        ),
    ]
