# Generated by Django 3.1 on 2020-10-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201002_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='merchant_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=20)),
                ('naiveuser_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.booking')),
            ],
        ),
    ]
