# Generated by Django 3.1 on 2020-10-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201003_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='naiveuser_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.booking'),
        ),
    ]
